version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=dice_game
      - DB_NAME_TEST=dice_game_test
      - DB_HOST=db
      - PORT=4000
    depends_on:
      - db
  
  admin:
    build:
      context: .
      dockerfile: ./admin/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:password@db/dice_game
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dice_game
      MYSQL_DATABASE_TEST: dice_game_test
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db-data:

